from fastapi import APIRouter, status, Query
from app.schemas.quiz_creation import (
    SourceUploadRequest,
    SourceUploadResponse,
    GenerateQuizRequest,
    GenerateQuizResponse,
    AnalysisResponse,
    TreeNode,
)

router = APIRouter()


@router.post("/upload", response_model=SourceUploadResponse, status_code=status.HTTP_201_CREATED)
async def upload_source(data: SourceUploadRequest):
    return SourceUploadResponse(
        sourceId=5001,
        message="Mock upload successful",
    )


@router.get("/analysis", response_model=AnalysisResponse)
async def get_analysis(sourceId: int = Query(..., description="Source ID")):
    # 現時点では sourceId はモックのため利用しない
    return AnalysisResponse(
        root=TreeNode(
            name="my-react-app",
            type="directory",
            description="Generated by LLM...",
            children=[
                TreeNode(
                    name="app",
                    type="directory",
                    description="アプリケーション本体のコード",
                    children=[
                        TreeNode(
                            name="api",
                            type="directory",
                            description="API レイヤ",
                            children=[
                                TreeNode(
                                    name="router.py",
                                    type="file",
                                    description="API ルーティング定義",
                                    children=[],
                                )
                            ],
                        ),
                        TreeNode(
                            name="services",
                            type="directory",
                            description="サービス層",
                            children=[
                                TreeNode(
                                    name="service.py",
                                    type="file",
                                    description="ユースケース・ビジネスロジック",
                                    children=[],
                                )
                            ],
                        ),
                        TreeNode(
                            name="main.py",
                            type="file",
                            description="アプリケーションのエントリポイント",
                            children=[],
                        ),
                    ],
                ),
                TreeNode(
                    name="tests",
                    type="directory",
                    description="テストコード",
                    children=[
                        TreeNode(
                            name="test_auth.py",
                            type="file",
                            description="認証まわりのテストコード",
                            children=[],
                        )
                    ],
                ),
            ],
        )
    )


@router.post("/generate", response_model=GenerateQuizResponse, status_code=status.HTTP_201_CREATED)
async def generate_quiz(data: GenerateQuizRequest):
    return GenerateQuizResponse(
        quizSetId=205,
    )
